# SPDX-FileCopyrightText: 2019 Bhushan Shah <bshah@kde.org>
#
# SPDX-License-Identifier: BSD-2-Clause
include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-reuse.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
