# SPDX-FileCopyrightText: 2024-2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: calindori
confinement: strict
grade: stable
base: core24
adopt-info: calindori
apps:
    calindori:
        extensions:
        - kde-neon-6
        common-id: org.kde.calindori.desktop
        desktop: usr/share/applications/org.kde.calindori.desktop
        command: usr/bin/calindori
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.calindori
        bus: session
parts:
    calindori:
        parse-info:
        - usr/share/metainfo/org.kde.calindori.appdata.xml
        plugin: cmake
        source: .
        source-type: local
        build-packages:
        - libxkbcommon-dev
        stage-packages:
        - libxkbcommon0
        cmake-parameters:
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DCMAKE_BUILD_TYPE=Release
        - -DQT_MAJOR_VERSION=6
        - -DBUILD_WITH_QT6=ON
        - -DBUILD_TESTING=OFF
        prime:
        - -usr/lib/*/cmake/*
        - -usr/include/*
        - -usr/share/ECM/*
        - -usr/share/man/*
        - -usr/bin/X11
        - -usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0
        - -usr/lib/aspell/*
        - -usr/share/lintian
    cleanup:
        after:
        - calindori
        plugin: nil
        build-snaps:
        - core24
        - kf6-core24
        override-prime: |
            set -eux
            for snap in "core24" "kf6-core24"; do
                cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
            done


